//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Genres
    {
        public int GenreId { get; set; }
        public string Name { get; set; }
    
        public virtual Genres ParidId { get; set; }
        public virtual Genres PrevidId { get; set; }
    }
}
